{{- if .Values.acr.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.acr.authSecret }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-webhook-controller.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.acr.dockerConfigJson | b64enc | quote }}
{{- end }}