apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "helm-webhook-controller.fullname" . }}
  labels:
    {{- include "helm-webhook-controller.labels" . | nindent 4 }}
webhooks:
- name: helm-registry.webhook.io
  admissionReviewVersions: ["v1", "v1beta1"]
  clientConfig:
    service:
      name: {{ include "helm-webhook-controller.fullname" . }}
      namespace: {{ .Values.namespace }}
      path: "/mutate"
    caBundle: {{ .Values.webhook.caBundle }}
  rules:
  - apiGroups: ["source.toolkit.fluxcd.io"]
    apiVersions: ["v1", "v1beta1", "v1beta2"]
    resources: ["helmrepositories"]
    operations: ["CREATE", "UPDATE"]
  namespaceSelector:
    matchExpressions:
    {{- if .Values.webhook.namespaceSelector }}
    {{- toYaml .Values.webhook.namespaceSelector | nindent 4 }}
    {{- else }}
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values: ["kube-system", "kube-public", "kube-node-lease", {{ .Values.namespace | quote }}]
    {{- end }}
  sideEffects: None
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}