apiVersion: v1
kind: Service
metadata:
  name: helm-webhook-controller
  namespace: helm-webhook-system
  labels:
    app.kubernetes.io/name: helm-webhook-controller
    app.kubernetes.io/part-of: helm-webhook-system
spec:
  type: ClusterIP
  ports:
  - name: webhook
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app.kubernetes.io/name: helm-webhook-controller