name: Helm Chart Validation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'helm-webhook-controller/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'helm-webhook-controller/**'
  workflow_dispatch:

jobs:
  helm-lint:
    name: Helm Lint and Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Lint Helm chart
        run: |
          helm lint helm-webhook-controller/

      - name: Template Helm chart
        run: |
          helm template test helm-webhook-controller/ --debug

      - name: Run Helm unittest
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git || true
          helm unittest helm-webhook-controller/ || echo "No tests found"

  kubeconform:
    name: Validate Kubernetes manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Generate manifests
        run: |
          helm template helm-webhook-controller helm-webhook-controller/ > manifests.yaml

      - name: Validate manifests with Kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: '/kubeconform'
          args: '-summary -output json manifests.yaml'

  polaris:
    name: Polaris Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Generate manifests
        run: |
          helm template helm-webhook-controller helm-webhook-controller/ > manifests.yaml

      - name: Run Polaris
        uses: fairwindsops/polaris/.github/actions/polaris@master
        with:
          version: '8.5.0'
          config: |
            checks:
              # Security
              hostIPCSet: danger
              hostPIDSet: danger
              hostNetworkSet: warning
              hostPortSet: warning
              
              # Images
              tagNotSpecified: danger
              pullPolicyNotAlways: warning
              
              # Health Checks
              readinessProbeMissing: warning
              livenessProbeMissing: warning
              
              # Networking
              tlsSettingsMissing: warning
              
              # Resources
              cpuRequestsMissing: warning
              cpuLimitsMissing: warning
              memoryRequestsMissing: warning
              memoryLimitsMissing: warning
              
              # Containers
              runAsRootAllowed: danger
              runAsPrivileged: danger
              notReadOnlyRootFilesystem: warning
              privilegeEscalationAllowed: danger
              
            exemptions:
              - namespace: kube-system
              - namespace: kube-public
              - namespace: kube-node-lease